# -*- coding: utf-8 -*-
"""ct208_binary_insertion_sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12aQRdzXdZG-YLnIOrk43UcIPB0Qj0cfc
"""

# @title
# Daniela America da Silva
# Exemplos de implementação caso medio binary insertion sort
# utilizei como exemplo https://www.sanfoundry.com/python-program-implement-binary-insertion-sort/
# ajustei para plotar a performance no tempo

from itertools import permutations 
import numpy as np 
import time, datetime
import matplotlib.pyplot as plt

def cria_lista (num):
   n = 0
   lista = []
   while n < num:
     lista.append(n+1)
     n+=1
   return (lista)


def binary_insertion_sort(alist):
    iter=0
    for i in range(1, len(alist)):
        temp = alist[i]
        pos = binary_search(alist, temp, 0, i) + 1
        for k in range(i, pos, -1):
            alist[k] = alist[k - 1]
            iter+=1
 
        alist[pos] = temp
    return(iter)    
    
 
def binary_search(alist, key, start, end):
    '''If key is in the list at index p, then return p.
    If there are multiple such keys in the list, then return the index of any one.
    If key is not in the list and a < key < b where a and b are elements in the list, then return the index of a.
    If key is not in the list and key < a where a is the first element in the list, then return -1.
    Only elements with indexes start to end - 1 inclusive are considered.
    '''
    if end - start <= 1:
        if key < alist[start]:
            return start - 1
        else:
            return start
 
    mid = (start + end)//2
    if alist[mid] < key:
        return binary_search(alist, key, mid, end)
    elif alist[mid] > key:
        return binary_search(alist, key, start, mid)
    else:
        return mid
 
 
#alist = input('Enter the list of numbers: ').split()
#alist = [int(x) for x in alist]

def cria_lista (num):
   n = 0
   lista = []
   while n < num:
     lista.append(n+1)
     n+=1
   return (lista)

counter=0
t0=time.time()

times=[]
counters=[]

for i in range (2,11):
  num = cria_lista (i)
  perm = permutations (num)
  for alist in list(perm):
      trocas = 0
      alist = [int(x) for x in alist]
#      print('Unsorted list: ', end='')
#      print(alist)
      trocas=binary_insertion_sort(alist)
#      print('Sorted list: ', end='')
#      print(alist)
#      print('Trocas: ', end='')
#      print(trocas)

      counters.append(trocas)
      times.append(time.time() - t0)

plt.plot(times)
#plt.plot(counters)