# -*- coding: utf-8 -*-
"""ct208_vizinhancaNeumann.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CFhFLEt6IjPOxCjf2kdoVM7eRnjX_uGm
"""

# Vizinhanca de Von Neumann
# Daniela America da Silva
# Exemplos de implementação para formulacao matematica proposta na CT208

#start = '{0:05b}'.format(6)
start= [0,0,1,1,0]
v = [] + start
next=[0,0,0,0,0]
 
# inicializa mattrix de transicao 
t = [[0] * 6] * 6 
t[0] = start

#gera a matriz do automato

for i in range(5):
  for n in range(5):
    if (n==0):
      next[n] = ((int(v[n]) + int(v[n+1]))%2)
    else:
      if (n==4):
        next[n] = ((int(v[n-1]) + int(v[n]))%2)
      else:
        next[n] = ((int(v[n-1]) + int(v[n]) + int(v[n+1]) + int(v[n-1]))%2)
  
  v=[] + next
  t[i+1] = v

#print(t)

#calcula a vizinhança de Von Neumman
#inicializa a matriz
vn = [[0] * 6] * 6 

def prt_transicao():
  for i in range(6):
    print (t[i])

def prt_neumann():
  for i in range(6):
    print (vn[i])

def viz_neumann():
  next=[0,0,0,0,0]
  for i in range(6):
    for n in range(5):
      #print (i,n)
      #1a coluna, 1a linha
      if (n==0 and i==0):
        next[n] = ( int(t[i][n]) + int(t[i][n+1]) + int(t[i+1][n]) ) %2 
      #1a coluna, ultima linha
      elif (n==0 and i==5):
        next[n] = ( int(t[i][n]) + int(t[i][n+1]) + int(t[i-1][n]) ) %2
      #1a coluna, qualquer linha
      elif (n==0 and i>0 and  i<5):
        next[n] = ( int(t[i][n]) + int(t[i][n+1]) + int(t[i-1][n]) + int(t[i+1][n]) ) %2

      #Ultima coluna, 1a linha
      if (n==4 and i==0):
        next[n] = ( int(t[i][n]) + int(t[i][n-1]) + int(t[i+1][n]) ) %2 
      #Ultima coluna, ultima linha
      elif (n==4 and i==5):
        next[n] = ( int(t[i][n]) + int(t[i][n-1]) + int(t[i-1][n]) ) %2 
      #Ultima coluna, qualquer outra linha
      elif (n==4 and i>0 and  i<5):
        next[n] = ( int(t[i][n]) + int(t[i][n-1]) + int(t[i-1][n]) + int(t[i+1][n]) ) %2
    
      #Qualquer outra coluna da primeira linha 
      if (n>0 and n<4 and i==0):
        next[n] = ( int(t[i][n-1]) + int(t[i][n])+ int(t[i][n+1]) + int(t[i+1][n]) ) %2 
      #Qualquer outra coluna da ultima linha 
      elif (n>0 and n<4 and i==5):
       next[n] = ( int(t[i][n-1]) + int(t[i][n]) + int(t[i][n+1]) + int(t[i-1][n]) ) %2 
      #Qualquer outra coluna de qualquer linha 
      elif (i>0 and i<5 and n>0 and n<4):
       next[n] = ( int(t[i][n-1]) + int(t[i][n])+ int(t[i][n+1]) + int(t[i-1][n]) + int(t[i+1][n]) ) %2

    vn[i] = [] + next

print("Matriz de transição da automato aula passada c0=(0,0,1,1,0)")
prt_transicao();

print("Vizinhança Neumann automato aula passada")
viz_neumann();
prt_neumann();

print("Matriz de transição Diamond Neumann")
t[0]=[0,0,0,0,0]
t[1]=[0,0,0,0,0]
t[2]=[0,0,1,0,0]
t[3]=[0,0,0,0,0]
t[4]=[0,0,0,0,0]
t[5]=[0,0,0,0,0]
prt_transicao();
print("Vizinhança Diamond Neumann")
viz_neumann();
prt_neumann();
t=[]+vn